In [1]:
import torch
from torch import nn
import csv
import os
train_on_gpu=True

In [274]:
import re
from collections import Counter
import numpy as np
import csv

In [3]:
import helper

In [4]:
f=open("ieeesite_data_aug_1.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)

In [219]:
f=open("ieeesite_data_final.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)

In [273]:
 data_1[:20]

[['yo', 'gen_hi'],
 ['Heya', 'gen_hi'],
 ['Namaste', 'gen_hi'],
 ['Hey', 'gen_hi'],
 ['Great see to you!', 'gen_hi'],
 ['Ssup', 'gen_hi'],
 ['Whatup', 'gen_hi'],
 ['Yo', 'gen_hi'],
 ['hello', 'gen_hi'],
 ['Howdy', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['There hey!', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['Buddy hey!', 'gen_hi'],
 ['Hi support need', 'gen_hi'],
 ['Hii', 'gen_hi'],
 ['Heyo', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hello!', 'gen_hi']]

In [6]:
f=open("ieeesite_data_augmented.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)
f.close()

In [7]:
f=open("ieeesite_data.csv","r")
read=csv.reader(f)
data_2=[]
for i in read:
    if i :
        data_2.append(i)
f.close()

In [8]:
def clean(o):
    cleaned=[]
    for i in o:
        if i and i[0]!='' and i[0].count("nan")==0:
            cleaned.append(i)
    return cleaned

In [272]:
clean(data_2)[:20]

[['yo', 'For saying Hi/Hey/Hello'],
 ['Heya', 'For saying Hi/Hey/Hello'],
 ['Namaste', 'For saying Hi/Hey/Hello'],
 ['Hey', 'For saying Hi/Hey/Hello'],
 ['Great to see you!', 'For saying Hi/Hey/Hello'],
 ['Ssup', 'For saying Hi/Hey/Hello'],
 ['Whatup', 'For saying Hi/Hey/Hello'],
 ['Yo', 'For saying Hi/Hey/Hello'],
 ['hello', 'For saying Hi/Hey/Hello'],
 ['Howdy', 'For saying Hi/Hey/Hello'],
 ['hey there', 'For saying Hi/Hey/Hello'],
 ['Hey There!', 'For saying Hi/Hey/Hello'],
 ['Hello!', 'For saying Hi/Hey/Hello'],
 ['Hey there', 'For saying Hi/Hey/Hello'],
 ['Hey buddy !', 'For saying Hi/Hey/Hello'],
 ['Hi .. need support ', 'For saying Hi/Hey/Hello'],
 ['Hii', 'For saying Hi/Hey/Hello'],
 ['Heyo', 'For saying Hi/Hey/Hello'],
 ['Hello!', 'For saying Hi/Hey/Hello'],
 ['Hello there!', 'For saying Hi/Hey/Hello']]

In [221]:
data=clean(data_1)
for i in clean(data_2):
    data.append(i)

In [222]:
questions=[]
labels=[]
words=[]
for i in data:
    questions.append(i[0])
    labels.append(i[1])
    for j in i[0].split():
        words.append(j)
y=labels

In [223]:
words=list(set(words))
questions=questions

labels=list(set(labels))
dead_words=[]

In [270]:
for i in words:
    try:
        print("",end="")
    except KeyError:
        dead_words.append(i)

In [271]:
len(dead_words)

289

In [232]:
def preprocess(text):

    # Replace punctuation with tokens so we can use them in our model
    text = text.lower()
    text = text.replace('.', '')
    text = text.replace(',','')
    text = text.replace('"', '')
    text = text.replace(';', '')
    text = text.replace('!', '')
    text = text.replace('?', '')
    text = text.replace('(', '')
    text = text.replace(')', '')
    text = text.replace('--', '')
    text = text.replace('?', '')
    text = text.replace('\n', '')
    text = text.replace(':', '')
    
    return text

In [275]:
words[:20]

['monster',
 'branches?',
 'man?',
 'bonk',
 'Great',
 'it?',
 'intertwine?',
 'modality',
 'witch',
 'advise',
 'knows?',
 'chair',
 'observing',
 'consequence,',
 'pick',
 'movement',
 'random',
 'neighbouring',
 'yearly',
 'aboard?']

In [234]:
cleaned_words=[]
for i in words:
    if not i in dead_words:
        cleaned_words.append(preprocess(i))

In [235]:
word_to_int={}
int_to_word={}
for i,j in enumerate(cleaned_words,1):
    word_to_int.update({j:i})
for j,i in word_to_int.items():
    int_to_word.update({i:j})

In [236]:
label_to_int={}
int_to_label={}
for i,j in enumerate(labels):
    int_to_label.update({i:j})
for i,j in int_to_label.items():
    label_to_int.update({j:i})

In [237]:
y_int=[]


In [238]:
print(len(questions),len(y))

14341 14341


In [239]:
def pad_features(reviews_ints, seq_length):
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)
    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    return features

In [240]:
print(len(questions),len(y))

14341 14341


In [241]:
len(cleaned_words)

3873

In [242]:
questions_int=[]
question_int=[]
y_int=[]
for i,l in zip(questions,y):
    question_int=[]
    for j in i.split():
        if j in cleaned_words:
            question_int.append(word_to_int[j])
    if len(question_int):
        questions_int.append(question_int)
        y_int.append(label_to_int[l])
        

In [243]:
print(len(y_int),len(questions_int))

13972 13972


In [244]:
questions_int[:20]

[[1712],
 [2099],
 [3727],
 [3149],
 [3727],
 [3149],
 [483, 3301],
 [3727],
 [2519, 1432, 2812],
 [2812, 1432],
 [3393, 2054, 2700],
 [2812, 881, 3382],
 [3382],
 [2254, 1950],
 [2700, 2254],
 [2254, 2700, 3636],
 [3494],
 [3636, 3636],
 [3720, 3378],
 [3393, 2054, 2700]]

In [245]:
questions_int=np.array(questions_int)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [246]:
questions_int

array([list([1712]), list([2099]), list([3727]), ...,
       list([3144, 2269, 3223]),
       list([2732, 2700, 2938, 804, 1013, 3804, 3740]),
       list([2187, 3809, 2938, 1296, 3592])], dtype=object)

In [247]:
seq_length = 10
features = pad_features(questions_int, seq_length=seq_length)
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."


print(features[:40])

[[   0    0    0    0    0    0    0    0    0 1712]
 [   0    0    0    0    0    0    0    0    0 2099]
 [   0    0    0    0    0    0    0    0    0 3727]
 [   0    0    0    0    0    0    0    0    0 3149]
 [   0    0    0    0    0    0    0    0    0 3727]
 [   0    0    0    0    0    0    0    0    0 3149]
 [   0    0    0    0    0    0    0    0  483 3301]
 [   0    0    0    0    0    0    0    0    0 3727]
 [   0    0    0    0    0    0    0 2519 1432 2812]
 [   0    0    0    0    0    0    0    0 2812 1432]
 [   0    0    0    0    0    0    0 3393 2054 2700]
 [   0    0    0    0    0    0    0 2812  881 3382]
 [   0    0    0    0    0    0    0    0    0 3382]
 [   0    0    0    0    0    0    0    0 2254 1950]
 [   0    0    0    0    0    0    0    0 2700 2254]
 [   0    0    0    0    0    0    0 2254 2700 3636]
 [   0    0    0    0    0    0    0    0    0 3494]
 [   0    0    0    0    0    0    0    0 3636 3636]
 [   0    0    0    0    0    0    0    0 3720

In [248]:
len(labels)

27

In [249]:
split_frac = 0.9
master_intent=y_int
## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = master_intent[:split_idx], master_intent[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(12574, 10) 
Validation set: 	(699, 10) 
Test set: 		(699, 10)


In [250]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.Tensor(train_x), torch.Tensor(train_y))
valid_data = TensorDataset(torch.Tensor(val_x), torch.Tensor(val_y))
test_data = TensorDataset(torch.Tensor(test_x), torch.Tensor(test_y))

# dataloaders
batch_size = 1

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [251]:
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([1, 10])
Sample input: 
 tensor([[   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 3720., 3772.]])

Sample label size:  torch.Size([1])
Sample label: 
 tensor([11.])


Model Declaration ************************************************

In [252]:
train_on_gpu=True

In [253]:
import torch.nn as nn

class Semantic_Classifier(nn.Module):
   

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        super(Semantic_Classifier, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim*2, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
       
        batch_size = x.size(0)
        embeds = self.embedding(x)
        
        lstm_out, hidden = self.lstm(embeds, hidden)
        out = self.fc(torch.cat((torch.squeeze(hidden[0]),torch.squeeze(hidden[1])),0))
       
        sig_out = self.sig(out)
        sig_out = sig_out.view(batch_size, -1)
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden

In [254]:
import torch.nn as nn

class Word2vec_Embed(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(Word2vec_Embed, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

    def forward(self, x):
        embeds = self.embedding(x)
        return embeds

In [255]:
import torch.nn as nn
class Semantic_Classifier_2(nn.Module):
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        super(Semantic_Classifier_2, self).__init__()
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        # embedding and LSTM layers
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True)
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim*2, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
        batch_size = x.size(0)
        lstm_out, hidden = self.lstm(x, hidden)
        out = self.fc(torch.cat((torch.squeeze(hidden[0]),torch.squeeze(hidden[1])),0))
        sig_out = self.sig(out)
        sig_out = sig_out.view(batch_size, -1)
        return sig_out, hidden
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        return hidden

In [ ]:
net_1.embedding(inputs).shape

In [192]:
gg=Word2vec_Embed(vocab_size, embedding_dim)
print(gg)
gg.cuda()
q=gg.embedding(inputs)
print(q.shape)

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)
torch.Size([1, 10, 300])


Semantic_Classifier_2(
  (lstm): LSTM(300, 256, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=512, out_features=27, bias=True)
  (sig): Sigmoid()
)

In [257]:

vocab_size = len(cleaned_words)+1
output_size = 27
print(vocab_size,output_size)
embedding_dim = 300
hidden_dim = 256
n_layers = 1

# net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
net_1=Semantic_Classifier(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
gg=Word2vec_Embed(vocab_size, embedding_dim)
net_2=Semantic_Classifier_2(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
net_2.cuda()
gg.cuda()
print(net_1)
print(net_2)
print(gg)

3874 27
Semantic_Classifier(
  (embedding): Embedding(3874, 300)
  (lstm): LSTM(300, 256, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=512, out_features=27, bias=True)
  (sig): Sigmoid()
)
Semantic_Classifier_2(
  (lstm): LSTM(300, 256, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=512, out_features=27, bias=True)
  (sig): Sigmoid()
)
Word2vec_Embed(
  (embedding): Embedding(3874, 300)
)


In [258]:
lr=0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net_1.parameters(), lr=lr)

In [196]:
gg.embedding.requires_grad = False
for i,j in int_to_word.items():
    gg.embedding.weight[i]=helper.embed(j)

In [197]:
gg.eval()

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)

In [260]:
epochs = 10
counter = 0
print_every = 1000
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net_1.cuda()

net_1.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    net_1.train()
    h = net_1.init_hidden(batch_size)
    

    # batch loop
    for inputs, labels in train_loader:
        counter += 1


        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
            inputs=torch.tensor(inputs).to(torch.int64)
            labels=torch.tensor(labels).to(torch.long)

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net_1.zero_grad()

        # get the output from the model
        inputs=torch.tensor(inputs).to(torch.int64)
        labels=torch.tensor(labels).to(torch.long)
        net_1.train()
        output, h = net_1(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output, labels)
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net_1.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            net_1.eval()
            val_h = net_1.init_hidden(batch_size)
            val_losses = []
            a=[]
            net_1.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                
                val_h = tuple([each.data for each in val_h])
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
                    inputs=torch.tensor(inputs).to(torch.int64)
                    labels=torch.tensor(labels).to(torch.long)

                output, val_h = net_1(inputs, val_h)
                _,index=torch.topk(output,1)
                val_loss = criterion(output, labels)
                a.append(index.item()==labels.item())
            a=100*((a.count(1))/(a.count(0)+a.count(1)))
                

            val_losses.append(val_loss.item())
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.9f}...".format(loss.item()),
                  "Val Accuracy: {:.2f}%...".format(a),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:37: UserWarning: To copy construct from a te

Epoch: 1/10... Step: 1000... Loss: 2.557543278... Val Accuracy: 79.40%... Val Loss: 2.419858
Epoch: 1/10... Step: 2000... Loss: 2.372050524... Val Accuracy: 78.11%... Val Loss: 2.361984
Epoch: 1/10... Step: 3000... Loss: 2.415666580... Val Accuracy: 81.40%... Val Loss: 2.434218
Epoch: 1/10... Step: 4000... Loss: 2.357560873... Val Accuracy: 83.40%... Val Loss: 2.361439
Epoch: 1/10... Step: 5000... Loss: 2.416610718... Val Accuracy: 83.69%... Val Loss: 2.419628
Epoch: 1/10... Step: 6000... Loss: 2.389304876... Val Accuracy: 87.41%... Val Loss: 2.357728
Epoch: 1/10... Step: 7000... Loss: 3.351060867... Val Accuracy: 86.70%... Val Loss: 2.478923
Epoch: 1/10... Step: 8000... Loss: 2.422895432... Val Accuracy: 87.27%... Val Loss: 2.432930
Epoch: 1/10... Step: 9000... Loss: 2.370754480... Val Accuracy: 87.55%... Val Loss: 2.415745
Epoch: 1/10... Step: 10000... Loss: 2.357593536... Val Accuracy: 89.84%... Val Loss: 2.470538
Epoch: 1/10... Step: 11000... Loss: 2.357626677... Val Accuracy: 88.5

Epoch: 8/10... Step: 89000... Loss: 2.357554197... Val Accuracy: 94.56%... Val Loss: 2.357534
Epoch: 8/10... Step: 90000... Loss: 2.357533932... Val Accuracy: 94.85%... Val Loss: 2.357640
Epoch: 8/10... Step: 91000... Loss: 2.357533932... Val Accuracy: 94.85%... Val Loss: 2.357534
Epoch: 8/10... Step: 92000... Loss: 2.357533932... Val Accuracy: 94.71%... Val Loss: 2.357534
Epoch: 8/10... Step: 93000... Loss: 2.415499687... Val Accuracy: 94.56%... Val Loss: 2.357540
Epoch: 8/10... Step: 94000... Loss: 2.357533932... Val Accuracy: 94.85%... Val Loss: 2.357725
Epoch: 8/10... Step: 95000... Loss: 2.357533932... Val Accuracy: 94.56%... Val Loss: 2.357538
Epoch: 8/10... Step: 96000... Loss: 2.357533932... Val Accuracy: 94.85%... Val Loss: 2.357535
Epoch: 8/10... Step: 97000... Loss: 2.357533932... Val Accuracy: 94.28%... Val Loss: 2.357534
Epoch: 8/10... Step: 98000... Loss: 2.357533932... Val Accuracy: 94.42%... Val Loss: 2.357534
Epoch: 8/10... Step: 99000... Loss: 2.357534170... Val Accur

Validation and Test Results are available below

In [261]:
net_1.eval()
val_h = net_1.init_hidden(batch_size)
val_losses = []
a=[]
net_1.eval()
for inputs, labels in test_loader:
        val_h = tuple([each.data for each in val_h])

        if(train_on_gpu):
                inputs, labels = inputs.cuda(), labels.cuda()
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                
        output, val_h = net_1(inputs, val_h)
        _,index=torch.topk(output,1)
        a.append(index.item()==labels.item())
        val_loss = criterion(output, labels)
        for i in inputs.squeeze():
            if i:
                print(int_to_word[i.item()],end=" ")
        print('\t\tOUTPUT:',int_to_label[index.item()])
                
        
        
        val_losses.append(val_loss.item())
print( "Val Loss: {:.6f}".format(np.mean(val_losses)),"        Val_Acuuracy:",(a.count(1)/(a.count(0)+a.count(1)))*100)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


saying 		OUTPUT: gen_query
bye bye 		OUTPUT: gen_bye
someone who made me 		OUTPUT: gen_who_made
im having solution one problem 		OUTPUT: gen_help
how happen become part operator ieee 		OUTPUT: ieee_be_part_who
how surely blessed are you 		OUTPUT: ieee_how_long
right hello 		OUTPUT: gen_bye
can afford we collaborate with nasa 		OUTPUT: ieee_collab
give you new bot 		OUTPUT: gen_bot
can you not be no practical help aboard 		OUTPUT: gen_help
how much would we collaborate with ieee 		OUTPUT: ieee_collab
r u n u 		OUTPUT: gen_bot
can you tell yourself me about repositories contained on your 		OUTPUT: ieee_github
can we potentially have preliminary reports if current board 		OUTPUT: ieee_current_board
any serious idea about those 		OUTPUT: ieee_future_events
do you do evil religious 		OUTPUT: ieee_projects
are dogs an artificial 		OUTPUT: gen_bot
where can together i get in touch with ieee for 		OUTPUT: ieee_collab
any good chance 		OUTPUT: ieee_collab
how you may contact you 		OUTPUT: ieee_

how can they connect with are you 		OUTPUT: ieee_further_contact
why does ieee observers work with other about the baltic 		OUTPUT: ieee_other_college
below below is ieee 		OUTPUT: ieee_what
could be peter help carolyn out 		OUTPUT: gen_help
consider what events is ieee planning trends for future 		OUTPUT: ieee_future_events
what country do do you serve 		OUTPUT: gen_who_made
m honestly interested in actually operating around this whoever do 		OUTPUT: ieee_sponsor
what do you nice guys be 		OUTPUT: ieee_what_does
i all smiled thank thee 		OUTPUT: ieee_github
about i fear cannot be spare 		OUTPUT: ieee_be_part_who
think who wants your 		OUTPUT: gen_who_made
which article are the events you conduct 		OUTPUT: ieee_past_events
i deliberately say this 		OUTPUT: gen_query
wonder what ieee big event is coming 		OUTPUT: ieee_future_events
how quickly do you connected contact the other 		OUTPUT: ieee_other_college
what all great events does ieee can 		OUTPUT: ieee_past_events
do u collaborate f

when almost completely who are you 		OUTPUT: gen_human
are you ready in the particular need any sponsors 		OUTPUT: ieee_sponsor
who are their 		OUTPUT: gen_who_you
does ieee not do 		OUTPUT: ieee_what_does
who are the other heads ieee 		OUTPUT: ieee_current_board
bring me yo bout onto the projects ieee does 		OUTPUT: ieee_projects
what all important events ieee computers 		OUTPUT: ieee_past_events
what all our domains does my chapter 2 		OUTPUT: ieee_domains
what's gotta tech loop 		OUTPUT: ieee_techloop
how can it anybody get more info 		OUTPUT: ieee_further_contact
what are the biggest events ieee gamma vit has conducted 		OUTPUT: ieee_past_events
what can also you give me re contact 		OUTPUT: ieee_further_contact
back 		OUTPUT: ieee_techloop
hey i had told me question 		OUTPUT: gen_query
is shall we guys on amazon 		OUTPUT: ieee_github
i have missed your 		OUTPUT: gen_query
i with more details 		OUTPUT: ieee_further_contact
i wanna check out from the ieee network github repository 	

do you seek additional funding 		OUTPUT: ieee_sponsor
db can also be generic part i ieee 		OUTPUT: ieee_be_part_who
how can now we collaborate with ieee 		OUTPUT: ieee_collab
may i know here who these heads who hosting different 		OUTPUT: ieee_current_board
would practically everyone soon get know about the logical limitations 		OUTPUT: ieee_current_board
area r board members 		OUTPUT: ieee_current_board
please tell me everything about 		OUTPUT: ieee_techloop
where down can i put 		OUTPUT: ieee_social_media
if all can join ieee 		OUTPUT: ieee_be_part_who
may i have girlfriend 		OUTPUT: gen_query
what's s an insta 		OUTPUT: ieee_social_media
where are it your future 		OUTPUT: ieee_future_events
topic is google 		OUTPUT: ieee_techloop
what's every loop loop 		OUTPUT: ieee_techloop
see this diagram 		OUTPUT: gen_bye
say what happen ieee 		OUTPUT: ieee_what
how were you 		OUTPUT: gen_how_you
yup who's after all 		OUTPUT: gen_thanks
when was it ieee 		OUTPUT: ieee_how_long
can we all collab

ar yours s it vit gone 		OUTPUT: ieee_other_linked
which storage separation technologies would do you people decide 		OUTPUT: ieee_domains
what must ieee trust 		OUTPUT: ieee_what_does
what does your skin look look like 		OUTPUT: ieee_current_board
whore youre so pretty 		OUTPUT: gen_who_made
those who are you heads 		OUTPUT: ieee_current_board
where u want 		OUTPUT: gen_bot
what are missions they 		OUTPUT: ieee_projects
but get you in vit headed now after hiring 		OUTPUT: ieee_other_linked
who all are the current its board members ceo 		OUTPUT: ieee_current_board
am i so eligible again join 		OUTPUT: ieee_be_part_who
thank you very dear much 		OUTPUT: gen_thanks
moi au 		OUTPUT: gen_thanks
Val Loss: 2.383141         Val_Acuuracy: 97.42489270386267


In [265]:
net_1.eval()
val_h = net_1.init_hidden(batch_size)
val_losses = []
a=[]
net_1.eval()
for inputs, labels in valid_loader:
        val_h = tuple([each.data for each in val_h])

        if(train_on_gpu):
                inputs, labels = inputs.cuda(), labels.cuda()
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                
        output, val_h = net_1(inputs, val_h)
        _,index=torch.topk(output,1)
        a.append(index.item()==labels.item())
        val_loss = criterion(output, labels)
        for i in inputs.squeeze():
            if i:
                print(int_to_word[i.item()],end=" ")
        print('OUTPUT:',int_to_label[index.item()])
                
        
        
        val_losses.append(val_loss.item())
print( "Val Loss: {:.6f}".format(np.mean(val_losses)),"        Val_Acuuracy:",(a.count(1)/(a.count(0)+a.count(1)))*100)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


how long has ieee already been around OUTPUT: ieee_how_long
ais this also linked iq vit OUTPUT: ieee_other_linked
are you you OUTPUT: gen_bot
ta hii OUTPUT: gen_thanks
who do i know u OUTPUT: gen_who_you
unless you require OUTPUT: ieee_sponsor
can you tel OUTPUT: ieee_sponsor
what project do we do OUTPUT: ieee_projects
where is ieee what drives it OUTPUT: ieee_what
i more OUTPUT: ieee_further_contact
can also be part i ieee OUTPUT: ieee_be_part_who
what is this paper OUTPUT: ieee_techloop
what did the chapter relate OUTPUT: ieee_what_does
oh OUTPUT: gen_thanks
what does your skin look like OUTPUT: ieee_current_board
who meet the current board members OUTPUT: ieee_current_board
is sending data vit connected its OUTPUT: ieee_other_linked
which reflects the major events hosted by you OUTPUT: ieee_past_events
what kind software projects work does ieee OUTPUT: ieee_projects
want hear something about ieee OUTPUT: ieee_what
i am no thank thank OUTPUT: gen_thanks
do you help OUTPUT: gen_help
t

who truly is your OUTPUT: gen_who_made
can he tell me now your github OUTPUT: ieee_github
could you please help make me play out OUTPUT: gen_help
then what repos does ieee automatically have OUTPUT: ieee_github
compare different linked OUTPUT: ieee_other_college
google OUTPUT: gen_thanks
sell more than OUTPUT: gen_human
who nearly made OUTPUT: gen_who_made
great OUTPUT: gen_thanks
what our the ways in question ieee would sponsor OUTPUT: ieee_sponsor
are you in need bank sponsors OUTPUT: ieee_sponsor
tell ya how ieee works OUTPUT: ieee_what_does
did you tell me about us on loan OUTPUT: ieee_github
what does being the chapter pages contribute OUTPUT: ieee_what_does
when was ieee OUTPUT: ieee_how_long
shall i have OUTPUT: gen_query
what sorts events do we secretly organize OUTPUT: ieee_past_events
know you using any social OUTPUT: ieee_social_media
does ieee do it OUTPUT: ieee_what_does
what ieee signal is coming OUTPUT: ieee_future_events
how do i reach out lasting peace with ieee OUTPUT

how are the those other rival colleges linked closely OUTPUT: ieee_other_college
explain what domains does ieee OUTPUT: ieee_domains
what were OUTPUT: ieee_what
got question on you OUTPUT: gen_query
but what does ieee OUTPUT: ieee_projects
what are latest OUTPUT: ieee_what_does
wherever you need sponsorship OUTPUT: ieee_sponsor
what are they OUTPUT: ieee_projects
how are no other college ieee boards linked you OUTPUT: ieee_other_college
what else that stuff has ieee done OUTPUT: ieee_projects
or are you OUTPUT: gen_bot
may i know who will you really OUTPUT: gen_who_you
how old america is OUTPUT: ieee_how_long
can i get any OUTPUT: gen_help
can ibm take part OUTPUT: ieee_be_part_who
are there way i must be part 1 OUTPUT: ieee_be_part_who
see diagram OUTPUT: gen_bye
what all events ieee OUTPUT: ieee_past_events
was ieee OUTPUT: ieee_how_long
unless i need assistance OUTPUT: gen_help
what does ieee do OUTPUT: ieee_what_does
what is it that ieee code does us OUTPUT: ieee_projects
how old d

github repository OUTPUT: ieee_github
can u help OUTPUT: gen_help
since when has ieee been there OUTPUT: ieee_how_long
suppose thou shall reveal yourself OUTPUT: gen_who_you
its killing OUTPUT: gen_who_you
are other ieee implementations are way linked towards you OUTPUT: ieee_other_linked
can also you help OUTPUT: gen_help
what even could ieee OUTPUT: ieee_what
what shall you do at ieee OUTPUT: ieee_what_does
how can you yet help OUTPUT: gen_who_you
m or u r human OUTPUT: gen_human
what number projects ieee focus OUTPUT: ieee_projects
or other ieee chapters in isis linked OUTPUT: ieee_other_linked
ieee was ieee created OUTPUT: ieee_how_long
i want them watch what ieee OUTPUT: ieee_what_does
list board members OUTPUT: ieee_current_board
so does ieee vit often communicate with ieee other nursing OUTPUT: ieee_other_college
can we have reports if current board OUTPUT: ieee_current_board
what do you now OUTPUT: ieee_what_does
ne yo OUTPUT: ieee_other_linked
no OUTPUT: gen_query
what is is i

Model type 2 training process with pretrained embeddings

In [212]:
lr=0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net_2.parameters(), lr=lr)

In [201]:
epochs = 10
counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net_2.cuda()
    gg.cuda()
gg.eval()
net_2.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    net_2.train()
    h = net_2.init_hidden(batch_size)
    # batch loop
    for inputs, labels in train_loader:
        counter += 1
        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
            inputs=torch.tensor(inputs).to(torch.int64)
            labels=torch.tensor(labels).to(torch.long)

        h = tuple([each.data for each in h])
        net_2.zero_grad()
        inputs=torch.tensor(inputs).to(torch.int64)
        labels=torch.tensor(labels).to(torch.long)
        net_2.train()
        embed=gg(inputs)
        output, h = net_2(embed, h)

        # calculate the loss and perform backprop
        loss = criterion(output, labels)
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net_2.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            net_1.eval()
            val_h = net_2.init_hidden(batch_size)
            val_losses = []
            a=[]
            net_1.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                
                val_h = tuple([each.data for each in val_h])
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
                    inputs=torch.tensor(inputs).to(torch.int64)
                    labels=torch.tensor(labels).to(torch.long)

                embed=gg(inputs)
                output, val_h = net_2(embed, val_h)
                _,index=torch.topk(output,1)
                val_loss = criterion(output, labels)
                a.append(index.item()==labels.item())
            a=100*((a.count(1))/(a.count(0)+a.count(1)))
                

            val_losses.append(val_loss.item())
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.9f}...".format(loss.item()),
                  "Val Accuracy: {:.2f}%...".format(a),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:28: UserWarning: To copy construct from a te

RuntimeError: leaf variable has been moved into the graph interior

tensor([1], device='cuda:0')

In [112]:
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])

In [113]:
net_1.embedding(input)

tensor([[[-0.2293,  0.8980,  0.0916,  ...,  0.1030, -0.4555,  0.1457],
         [-0.3443,  0.1976, -0.4041,  ...,  1.4874,  1.6619, -1.9421],
         [ 2.0021, -0.5411,  0.3348,  ..., -0.4410, -1.4665, -1.4666],
         [-1.4639, -1.4073,  0.5237,  ...,  0.0995,  1.2004, -0.0285]],

        [[ 2.0021, -0.5411,  0.3348,  ..., -0.4410, -1.4665, -1.4666],
         [-0.9742,  1.2988, -1.2953,  ..., -0.6601,  1.0600, -0.3606],
         [-0.3443,  0.1976, -0.4041,  ...,  1.4874,  1.6619, -1.9421],
         [-1.3222,  1.3495, -1.5036,  ..., -0.7361,  0.6563,  0.0972]]],
       grad_fn=<EmbeddingBackward>)

In [64]:
net_1.embedding.weight

Parameter containing:
tensor([[-2.7655e-01,  1.0842e+00, -2.0595e+00,  ..., -5.9035e-01,
          9.9509e-01,  1.5742e+00],
        [ 4.3328e-01, -6.1953e-02, -9.6089e-02,  ..., -1.2927e+00,
         -8.9933e-01,  6.1164e-02],
        [-3.6420e-01,  6.4138e-01, -1.5965e+00,  ...,  3.2847e-01,
         -1.7789e+00,  2.6770e-01],
        ...,
        [ 1.5111e+00, -9.9730e-01, -1.4124e+00,  ...,  4.6116e-02,
          9.1095e-01,  5.6723e-02],
        [-1.1536e+00, -2.4567e-01,  4.1004e-01,  ..., -3.1223e+00,
          1.2800e-01,  6.4361e-01],
        [ 1.0157e+00,  2.8516e-01, -4.8914e-02,  ...,  5.9363e-01,
         -2.5761e-03,  2.3110e-01]], device='cuda:0', requires_grad=True)

In [262]:
torch.save(net_1,"ieeesite_v1.pt")

In [213]:
outputs,_=net_2(gg(inputs),net_2.init_hidden(1))

In [217]:
loss = criterion(output, labels)
loss.backward(retain_graph=True)
      # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
nn.utils.clip_grad_norm_(net_2.parameters(), clip)
optimizer.step()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)