In [1]:
import torch
from torch import nn
import csv
import os
train_on_gpu=True

In [2]:
import re
from collections import Counter
import numpy as np
import csv

In [3]:
import helper

In [4]:
f=open("ieeesite_data_aug_1.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)

In [6]:
f=open("ieeesite_data_final.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)

In [7]:
 data_1[:20]

[['yo', 'gen_hi'],
 ['Heya', 'gen_hi'],
 ['Namaste', 'gen_hi'],
 ['Hey', 'gen_hi'],
 ['Great see to you!', 'gen_hi'],
 ['Ssup', 'gen_hi'],
 ['Whatup', 'gen_hi'],
 ['Yo', 'gen_hi'],
 ['hello', 'gen_hi'],
 ['Howdy', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['There hey!', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['Buddy hey!', 'gen_hi'],
 ['Hi support need', 'gen_hi'],
 ['Hii', 'gen_hi'],
 ['Heyo', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hello!', 'gen_hi']]

In [6]:
f=open("ieeesite_data_augmented.csv","r")
read=csv.reader(f)
data_1=[]
for i in read:
    if i :
        data_1.append(i)
f.close()

In [7]:
f=open("ieeesite_data.csv","r")
read=csv.reader(f)
data_2=[]
for i in read:
    if i :
        data_2.append(i)
f.close()

In [9]:
def clean(o):
    cleaned=[]
    for i in o:
        if i and i[0]!='' and i[0].count("nan")==0:
            cleaned.append(i)
    return cleaned

In [11]:
clean(data_1)[:20]

[['yo', 'gen_hi'],
 ['Heya', 'gen_hi'],
 ['Namaste', 'gen_hi'],
 ['Hey', 'gen_hi'],
 ['Great see to you!', 'gen_hi'],
 ['Ssup', 'gen_hi'],
 ['Whatup', 'gen_hi'],
 ['Yo', 'gen_hi'],
 ['hello', 'gen_hi'],
 ['Howdy', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['There hey!', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['Buddy hey!', 'gen_hi'],
 ['Hi support need', 'gen_hi'],
 ['Hii', 'gen_hi'],
 ['Heyo', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hello!', 'gen_hi']]

In [13]:
data

[['yo', 'gen_hi'],
 ['Heya', 'gen_hi'],
 ['Namaste', 'gen_hi'],
 ['Hey', 'gen_hi'],
 ['Great see to you!', 'gen_hi'],
 ['Ssup', 'gen_hi'],
 ['Whatup', 'gen_hi'],
 ['Yo', 'gen_hi'],
 ['hello', 'gen_hi'],
 ['Howdy', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['There hey!', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hey', 'gen_hi'],
 ['Buddy hey!', 'gen_hi'],
 ['Hi support need', 'gen_hi'],
 ['Hii', 'gen_hi'],
 ['Heyo', 'gen_hi'],
 ['! hello', 'gen_hi'],
 ['There hello!', 'gen_hi'],
 ['There hello!', 'gen_hi'],
 ['Yo', 'gen_hi'],
 ['Hii', 'gen_hi'],
 ["what ' up s", 'gen_how_you'],
 ["What s ' up", 'gen_how_you'],
 ['Wassup', 'gen_how_you'],
 ['How are doing you', 'gen_how_you'],
 ["How s ' treating life you?", 'gen_how_you'],
 ['How is? life', 'gen_how_you'],
 ['Ya how doin', 'gen_how_you'],
 ['Sup', 'gen_how_you'],
 ['you how doing?', 'gen_how_you'],
 ['Do how you do', 'gen_how_you'],
 ['? sup', 'gen_how_you'],
 ['How do do you?', 'gen_how_you'],
 ['How have you? been', 'gen_how_you'],
 ['H

In [12]:
data=clean(data_1)
for i in clean(data_2):
    data.append(i)

NameError: name 'data_2' is not defined

In [14]:
questions=[]
labels=[]
words=[]
for i in data:
    questions.append(i[0])
    labels.append(i[1])
    for j in i[0].split():
        words.append(j)
y=labels

In [15]:
words=list(set(words))
questions=questions

labels=list(set(labels))
dead_words=[]

In [16]:
for i in words:
    try:
        print("",end="")
    except KeyError:
        dead_words.append(i)

In [17]:
len(dead_words)

0

In [18]:
def preprocess(text):

    # Replace punctuation with tokens so we can use them in our model
    text = text.lower()
    text = text.replace('.', '')
    text = text.replace(',','')
    text = text.replace('"', '')
    text = text.replace(';', '')
    text = text.replace('!', '')
    text = text.replace('?', '')
    text = text.replace('(', '')
    text = text.replace(')', '')
    text = text.replace('--', '')
    text = text.replace('?', '')
    text = text.replace('\n', '')
    text = text.replace(':', '')
    
    return text

In [19]:
words[:20]

['recognize',
 'someone?',
 'with?',
 'sense',
 'confidence',
 'timely.',
 'clubs',
 'haunt',
 'loanword',
 'assure',
 'i.',
 'theater',
 'assort',
 'astir',
 'excessively',
 'that',
 'sees',
 'dress',
 'universal',
 'pls']

In [20]:
cleaned_words=[]
for i in words:
    if not i in dead_words:
        cleaned_words.append(preprocess(i))

In [21]:
word_to_int={}
int_to_word={}
for i,j in enumerate(cleaned_words,1):
    word_to_int.update({j:i})
for j,i in word_to_int.items():
    int_to_word.update({i:j})

In [22]:
label_to_int={}
int_to_label={}
for i,j in enumerate(labels):
    int_to_label.update({i:j})
for i,j in int_to_label.items():
    label_to_int.update({j:i})

In [23]:
y_int=[]


In [24]:
print(len(questions),len(y))

14341 14341


In [25]:
def pad_features(reviews_ints, seq_length):
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)
    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    return features

In [26]:
print(len(questions),len(y))

14341 14341


In [27]:
len(cleaned_words)

4162

In [28]:
questions_int=[]
question_int=[]
y_int=[]
for i,l in zip(questions,y):
    question_int=[]
    for j in i.split():
        if j in cleaned_words:
            question_int.append(word_to_int[j])
    if len(question_int):
        questions_int.append(question_int)
        y_int.append(label_to_int[l])
        

In [29]:
print(len(y_int),len(questions_int))

14018 14018


In [30]:
questions_int[:20]

[[4042],
 [3367, 3904],
 [1344],
 [2050],
 [1344],
 [2050],
 [2495, 3722],
 [1344],
 [3437, 3143, 2738, 2498],
 [2498, 3143, 2738],
 [3121, 3561, 2584],
 [2498, 3143, 2530, 3107],
 [3107],
 [3110, 3498],
 [2584, 3110],
 [3110, 2584, 4045],
 [3958],
 [4045, 4045],
 [3136, 3650],
 [3121, 3561, 2584]]

In [31]:
questions_int=np.array(questions_int)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [32]:
questions_int

array([list([4042]), list([3367, 3904]), list([1344]), ...,
       list([2758, 2833, 3850]),
       list([3563, 2584, 3624, 890, 2207, 3843, 3991]),
       list([3050, 4031, 3624, 2411, 3662])], dtype=object)

In [73]:
type(questions_int)

numpy.ndarray

In [33]:
seq_length = 10
features = pad_features(questions_int, seq_length=seq_length)
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."


print(features[:40])

[[   0    0    0    0    0    0    0    0    0 4042]
 [   0    0    0    0    0    0    0    0 3367 3904]
 [   0    0    0    0    0    0    0    0    0 1344]
 [   0    0    0    0    0    0    0    0    0 2050]
 [   0    0    0    0    0    0    0    0    0 1344]
 [   0    0    0    0    0    0    0    0    0 2050]
 [   0    0    0    0    0    0    0    0 2495 3722]
 [   0    0    0    0    0    0    0    0    0 1344]
 [   0    0    0    0    0    0 3437 3143 2738 2498]
 [   0    0    0    0    0    0    0 2498 3143 2738]
 [   0    0    0    0    0    0    0 3121 3561 2584]
 [   0    0    0    0    0    0 2498 3143 2530 3107]
 [   0    0    0    0    0    0    0    0    0 3107]
 [   0    0    0    0    0    0    0    0 3110 3498]
 [   0    0    0    0    0    0    0    0 2584 3110]
 [   0    0    0    0    0    0    0 3110 2584 4045]
 [   0    0    0    0    0    0    0    0    0 3958]
 [   0    0    0    0    0    0    0    0 4045 4045]
 [   0    0    0    0    0    0    0    0 3136

In [34]:
len(labels)

27

In [35]:
split_frac = 0.9
master_intent=y_int
## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = master_intent[:split_idx], master_intent[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(12616, 10) 
Validation set: 	(701, 10) 
Test set: 		(701, 10)


In [36]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.Tensor(train_x), torch.Tensor(train_y))
valid_data = TensorDataset(torch.Tensor(val_x), torch.Tensor(val_y))
test_data = TensorDataset(torch.Tensor(test_x), torch.Tensor(test_y))

# dataloaders
batch_size = 1

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [37]:
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([1, 10])
Sample input: 
 tensor([[   0.,    0.,    0.,    0.,    0., 3898., 1873., 3138., 3624., 1847.]])

Sample label size:  torch.Size([1])
Sample label: 
 tensor([5.])


Model Declaration ************************************************

In [38]:
train_on_gpu=True

In [39]:
import torch.nn as nn
#

In [254]:
import torch.nn as nn

class Word2vec_Embed(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(Word2vec_Embed, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

    def forward(self, x):
        embeds = self.embedding(x)
        return embeds

In [255]:
import torch.nn as nn
class Semantic_Classifier_2(nn.Module):
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        super(Semantic_Classifier_2, self).__init__()
        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        # embedding and LSTM layers
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True)
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim*2, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
        batch_size = x.size(0)
        lstm_out, hidden = self.lstm(x, hidden)
        out = self.fc(torch.cat((torch.squeeze(hidden[0]),torch.squeeze(hidden[1])),0))
        sig_out = self.sig(out)
        sig_out = sig_out.view(batch_size, -1)
        return sig_out, hidden
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        return hidden

In [ ]:
net_1.embedding(inputs).shape

In [192]:
gg=Word2vec_Embed(vocab_size, embedding_dim)
print(gg)
gg.cuda()
q=gg.embedding(inputs)
print(q.shape)

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)
torch.Size([1, 10, 300])


Semantic_Classifier_2(
  (lstm): LSTM(300, 256, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=512, out_features=27, bias=True)
  (sig): Sigmoid()
)

In [64]:
len(cleaned_words)

4162

In [40]:

vocab_size = len(cleaned_words)+1
output_size = 27
print(vocab_size,output_size)
embedding_dim = 300
hidden_dim = 256
n_layers = 1

# net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
net_1=Semantic_Classifier(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
gg=Word2vec_Embed(vocab_size, embedding_dim)
net_2=Semantic_Classifier_2(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
net_2.cuda()
gg.cuda()
print(net_1)
print(net_2)
print(gg)

4163 27


C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\rnn.py:60: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


NameError: name 'Word2vec_Embed' is not defined

In [41]:
lr=0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net_1.parameters(), lr=lr)

In [196]:
gg.embedding.requires_grad = False
for i,j in int_to_word.items():
    gg.embedding.weight[i]=helper.embed(j)

In [197]:
gg.eval()

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)

In [42]:
epochs = 10
counter = 0
print_every = 1000
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net_1.cuda()

net_1.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    net_1.train()
    h = net_1.init_hidden(batch_size)
    

    # batch loop
    for inputs, labels in train_loader:
        counter += 1


        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
            inputs=torch.tensor(inputs).to(torch.int64)
            labels=torch.tensor(labels).to(torch.long)

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net_1.zero_grad()

        # get the output from the model
        inputs=torch.tensor(inputs).to(torch.int64)
        labels=torch.tensor(labels).to(torch.long)
        net_1.train()
        output, h = net_1(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output, labels)
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net_1.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            net_1.eval()
            val_h = net_1.init_hidden(batch_size)
            val_losses = []
            a=[]
            net_1.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                
                val_h = tuple([each.data for each in val_h])
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
                    inputs=torch.tensor(inputs).to(torch.int64)
                    labels=torch.tensor(labels).to(torch.long)

                output, val_h = net_1(inputs, val_h)
                _,index=torch.topk(output,1)
                val_loss = criterion(output, labels)
                a.append(index.item()==labels.item())
            a=100*((a.count(1))/(a.count(0)+a.count(1)))
                

            val_losses.append(val_loss.item())
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.9f}...".format(loss.item()),
                  "Val Accuracy: {:.2f}%...".format(a),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:25: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:36: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:37: UserWarning: To copy construct from a te

Epoch: 1/10... Step: 1000... Loss: 3.267796993... Val Accuracy: 60.34%... Val Loss: 2.455271
Epoch: 1/10... Step: 2000... Loss: 2.466945410... Val Accuracy: 72.90%... Val Loss: 2.471189
Epoch: 1/10... Step: 3000... Loss: 3.300851345... Val Accuracy: 82.74%... Val Loss: 2.371645
Epoch: 1/10... Step: 4000... Loss: 2.542634487... Val Accuracy: 84.02%... Val Loss: 2.414321
Epoch: 1/10... Step: 5000... Loss: 2.463744879... Val Accuracy: 85.45%... Val Loss: 2.428932
Epoch: 1/10... Step: 6000... Loss: 2.612277985... Val Accuracy: 85.16%... Val Loss: 2.359193
Epoch: 1/10... Step: 7000... Loss: 2.440933228... Val Accuracy: 88.30%... Val Loss: 2.379679
Epoch: 1/10... Step: 8000... Loss: 3.442874908... Val Accuracy: 88.87%... Val Loss: 2.415702
Epoch: 1/10... Step: 9000... Loss: 2.415557146... Val Accuracy: 87.59%... Val Loss: 2.532825
Epoch: 1/10... Step: 10000... Loss: 2.420017242... Val Accuracy: 89.73%... Val Loss: 2.357632
Epoch: 1/10... Step: 11000... Loss: 2.357536316... Val Accuracy: 88.8

Epoch: 8/10... Step: 89000... Loss: 2.357533932... Val Accuracy: 97.57%... Val Loss: 2.357538
Epoch: 8/10... Step: 90000... Loss: 2.357533932... Val Accuracy: 97.15%... Val Loss: 2.357534
Epoch: 8/10... Step: 91000... Loss: 2.357533932... Val Accuracy: 97.29%... Val Loss: 2.357534
Epoch: 8/10... Step: 92000... Loss: 2.357533932... Val Accuracy: 97.43%... Val Loss: 2.357534
Epoch: 8/10... Step: 93000... Loss: 3.357481480... Val Accuracy: 97.15%... Val Loss: 2.357534
Epoch: 8/10... Step: 94000... Loss: 2.415908575... Val Accuracy: 97.72%... Val Loss: 2.357534
Epoch: 8/10... Step: 95000... Loss: 2.357534647... Val Accuracy: 97.29%... Val Loss: 2.357564
Epoch: 8/10... Step: 96000... Loss: 2.357534170... Val Accuracy: 97.00%... Val Loss: 2.358963
Epoch: 8/10... Step: 97000... Loss: 2.416239500... Val Accuracy: 97.57%... Val Loss: 2.357534
Epoch: 8/10... Step: 98000... Loss: 2.357533932... Val Accuracy: 97.43%... Val Loss: 2.357534
Epoch: 8/10... Step: 99000... Loss: 2.357533932... Val Accur

Validation and Test Results are available below

In [47]:
net_1.eval()
val_h = net_1.init_hidden(batch_size)
val_losses = []
a=[]
net_1.eval()
for inputs, labels in test_loader:
        val_h = tuple([each.data for each in val_h])

        if(train_on_gpu):
                inputs, labels = inputs.cuda(), labels.cuda()
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                
        output, val_h = net_1(inputs, val_h)
        _,index=torch.topk(output,1)
        a.append(index.item()==labels.item())
        val_loss = criterion(output, labels)
        for i in inputs.squeeze():
            if i:
                print(int_to_word[i.item()],end=" ")
        print('\t\tOUTPUT:',int_to_label[index.item()])
                
        
        
        val_losses.append(val_loss.item())
print( "Val Loss: {:.6f}".format(np.mean(val_losses)),"        Val_Acuuracy:",(a.count(1)/(a.count(0)+a.count(1)))*100)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


can i be given a part 		OUTPUT: ieee_be_part_who
whether all ieees shipped from japan are 		OUTPUT: ieee_other_linked
ibm and is 		OUTPUT: ieee_what
oh hey u domains do u n guys do 		OUTPUT: ieee_domains
what are the estimated future 		OUTPUT: ieee_future_events
if i wanted to ask her 		OUTPUT: gen_query
are t there a way i must naturally be fulfilling 		OUTPUT: ieee_be_part_who
if are there any difference between between the aforementioned ieee 		OUTPUT: ieee_other_linked
i wannt with more details 		OUTPUT: ieee_further_contact
well thanks for dropping me 		OUTPUT: gen_thanks
are dragons a magical 		OUTPUT: gen_bot
imagine whatever owns 		OUTPUT: gen_who_made
who served are current board 		OUTPUT: ieee_current_board
so are we 		OUTPUT: gen_human
what all our domains does my chapter 2 		OUTPUT: ieee_domains
what happened are upcoming ieee events 		OUTPUT: ieee_future_events
imagine what could you do 		OUTPUT: ieee_projects
who are the other heads of ieee 		OUTPUT: ieee_current_board
so

what became this original website 		OUTPUT: ieee_what
name some of famous verses spoken among urs 		OUTPUT: ieee_past_events
so wherever do they call you 		OUTPUT: gen_who_you
compare 34 different ieees linked 		OUTPUT: ieee_other_college
what's ieee'on s an insta 		OUTPUT: ieee_social_media
pray u answer upon my doubts 		OUTPUT: gen_query
who likewise can join ieee 		OUTPUT: ieee_be_part_who
are you buying her robot or a ghost 		OUTPUT: gen_human
thankyou for spilling the 		OUTPUT: gen_thanks
if all can join ieee 		OUTPUT: ieee_be_part_who
invited to freely join ieee 		OUTPUT: ieee_be_part_who
telling me about behind the past events 		OUTPUT: ieee_past_events
are you not 		OUTPUT: gen_bot
just where can i ask 		OUTPUT: ieee_social_media
why may i the identity of another 		OUTPUT: gen_who_you
does ieee ignition cause 		OUTPUT: ieee_what_does
what details are ieee's contact 		OUTPUT: ieee_further_contact
i have got some problems 		OUTPUT: gen_query
how quickly do you connected and conta

patient appreciate compassionate help 		OUTPUT: gen_thanks
whore youre so pretty 		OUTPUT: gen_who_made
so what is techloop singing 		OUTPUT: ieee_techloop
how can it anybody get more info 		OUTPUT: ieee_further_contact
shows how they became linked 		OUTPUT: ieee_other_college
this's still the age of alpha galactic 		OUTPUT: ieee_how_long
ar yours ieee'what s it a vit gone 		OUTPUT: ieee_other_linked
who can formally join ieee 		OUTPUT: ieee_be_part_who
what is exactly your 		OUTPUT: ieee_techloop
anyway she ain't enough think you't re only a you 		OUTPUT: gen_human
now tell me what about github 		OUTPUT: ieee_github
why can ieee have different 		OUTPUT: ieee_other_linked
nobody can and i get that of ur social media 		OUTPUT: ieee_social_media
what would you dare do 		OUTPUT: ieee_future_events
moi au 		OUTPUT: gen_thanks
eat what're your socials 		OUTPUT: ieee_social_media
where can i really contact 		OUTPUT: ieee_social_media
why are you on any social gaming 		OUTPUT: ieee_social_med

who is holding your queen 		OUTPUT: gen_who_made
show up me your github comic repos 		OUTPUT: ieee_github
any other bonus info 		OUTPUT: ieee_further_contact
how are compare the ieees of other nations comparable compared 		OUTPUT: ieee_other_college
any probable future programs 		OUTPUT: ieee_future_events
round 6 bye 		OUTPUT: gen_bye
how do we ever get in touch with either you 		OUTPUT: ieee_further_contact
explore what are techloops 		OUTPUT: ieee_techloop
shareholders who are the total fifteen board members per ieee 		OUTPUT: ieee_current_board
do have you conduct 		OUTPUT: ieee_past_events
ever goodbye 		OUTPUT: gen_bye
any contact any info 		OUTPUT: ieee_further_contact
you wouldnt wish her to be a witch long would 		OUTPUT: gen_bot
dear dear parents 		OUTPUT: ieee_what
robbie 		OUTPUT: gen_thanks
last bye night 		OUTPUT: gen_bye
how courage to join ieee 		OUTPUT: ieee_be_part_who
can businesses now get real touch with ieee applications pending 		OUTPUT: ieee_collab
do u collabor

lucky you one one of us 		OUTPUT: gen_human
ok what is 		OUTPUT: ieee_techloop
what is your photographic identification 		OUTPUT: ieee_social_media
how too old are ieee 		OUTPUT: ieee_how_long
what parties are some the projects parties are participating actively 		OUTPUT: ieee_projects
know what software projects do we do 		OUTPUT: ieee_projects
how badly did you doing 		OUTPUT: gen_how_you
your usual facebook pages 		OUTPUT: ieee_social_media
that particular old guy named harsh 		OUTPUT: gen_who_made
we may i know who the heads have of the 		OUTPUT: ieee_current_board
how do we 		OUTPUT: ieee_be_part_who
where can i now get a your contact info 		OUTPUT: ieee_further_contact
any idea about potential future 		OUTPUT: ieee_future_events
lucky are you ever bot 		OUTPUT: gen_bot
wondering how to contact you 		OUTPUT: ieee_further_contact
makes you mean a 		OUTPUT: gen_human
indeed do so they do 		OUTPUT: ieee_what_does
i seldom shall understand 		OUTPUT: gen_query
what are the stories 		OU

In [44]:
net_1.eval()
val_h = net_1.init_hidden(batch_size)
val_losses = []
a=[]
net_1.eval()
for inputs, labels in valid_loader:
        val_h = tuple([each.data for each in val_h])

        if(train_on_gpu):
                inputs, labels = inputs.cuda(), labels.cuda()
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                
        output, val_h = net_1(inputs, val_h)
        _,index=torch.topk(output,1)
        a.append(index.item()==labels.item())
        val_loss = criterion(output, labels)
        for i in inputs.squeeze():
            if i:
                print(int_to_word[i.item()],end=" ")
        print('OUTPUT:',int_to_label[index.item()])
                
        
        
        val_losses.append(val_loss.item())
print( "Val Loss: {:.6f}".format(np.mean(val_losses)),"        Val_Acuuracy:",(a.count(1)/(a.count(0)+a.count(1)))*100)

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  if sys.path[0] == '':


below is ieee OUTPUT: ieee_what
are you killing OUTPUT: gen_human
how do you connected and the other ieees OUTPUT: ieee_other_college
explain information about ieee OUTPUT: ieee_what
any chance of OUTPUT: ieee_collab
need by your help OUTPUT: gen_help
what are the projects currently that are done legally under OUTPUT: ieee_projects
who sees can be most part of a OUTPUT: ieee_be_part_who
who really created OUTPUT: gen_who_made
these are upcoming ieee events OUTPUT: ieee_future_events
wonder what wonderful kind of stuff has ieee done OUTPUT: ieee_projects
i have escaped a doubt from lingering firmly in my OUTPUT: gen_query
oh heya OUTPUT: gen_hi
what data is ieee OUTPUT: ieee_what
what are ieee's latest OUTPUT: ieee_further_contact
i have the question OUTPUT: gen_query
does ieee of other languages apply to you OUTPUT: ieee_other_college
how must i collaborate with dumb guys OUTPUT: ieee_collab
forgive you for solving my OUTPUT: gen_thanks
i'm interested in operating this whoever do i OUT

tell me about the wikipedia projects ieee wikipedia does OUTPUT: ieee_projects
look what is OUTPUT: ieee_what
what category of projects does ieee OUTPUT: ieee_projects
can i get that of ur social media address OUTPUT: ieee_social_media
how so do you OUTPUT: gen_how_you
anything does ieee OUTPUT: ieee_projects
are thus the other ieees with specialisations commonly linked together OUTPUT: ieee_other_linked
ieee exactly OUTPUT: ieee_what
is ieee - wie definition 0 OUTPUT: ieee_other_linked
do i still have any objection to other ieees OUTPUT: ieee_other_college
who would you do OUTPUT: ieee_future_events
who created after OUTPUT: gen_who_made
got its OUTPUT: gen_who_you
what sorts of events do we secretly organize OUTPUT: ieee_past_events
how they became linked OUTPUT: ieee_other_college
source is ieee OUTPUT: ieee_what
what exactly your OUTPUT: ieee_techloop
what is it that ieee code does us OUTPUT: ieee_projects
what is ieee - wie formally part of OUTPUT: ieee_other_linked
what kind numb

recall what domains r there OUTPUT: ieee_domains
universal OUTPUT: gen_who_you
can we meet OUTPUT: ieee_collab
pray u answer my doubts OUTPUT: gen_query
maybe i have a question OUTPUT: gen_query
what jobs do you do at ieee OUTPUT: ieee_what_does
are there other ieee chapters indexed in vit linked to OUTPUT: ieee_other_linked
what did the chapter relate OUTPUT: ieee_what_does
i have lost OUTPUT: gen_query
what'isn s the age distribution of this OUTPUT: ieee_how_long
what are the various operational sub research divisions of ieee OUTPUT: ieee_domains
what do they make at ieee OUTPUT: ieee_projects
tell me uncle OUTPUT: ieee_techloop
give me an overview of the domains you know OUTPUT: ieee_domains
does ieee observers work with other ieees about the OUTPUT: ieee_other_college
can anyone collaborate with a OUTPUT: ieee_collab
whens your 57th OUTPUT: ieee_how_long
find me OUTPUT: gen_help
i have no doubt OUTPUT: gen_query
what we ieee do OUTPUT: ieee_what_does
can anybody do me a favor OUTPU

how old is last chapter OUTPUT: ieee_how_long
who knows art thy creator OUTPUT: gen_who_made
i definitely have a question to ask OUTPUT: gen_query
i shall understand OUTPUT: gen_query
would something help OUTPUT: gen_help
are we OUTPUT: gen_human
do we provide ieee some legal OUTPUT: ieee_sponsor
can you solve my eternal OUTPUT: gen_query
no kind of projects do u say doo OUTPUT: ieee_projects
any events held up OUTPUT: ieee_future_events
does ieee phone deed chance need OUTPUT: ieee_sponsor
considering what shape is the relation difference between ieees of OUTPUT: ieee_other_college
may we roll with ieee or do an event OUTPUT: ieee_collab
darling whore youre parents OUTPUT: gen_who_made
where are the events ieee vit you brought in geologic OUTPUT: ieee_past_events
give yourselves a list of domains OUTPUT: ieee_domains
what is this the same ieee which i see in OUTPUT: ieee_other_linked
who are the total board members per ieee OUTPUT: ieee_current_board
which are the domains of you are a

Model type 2 training process with pretrained embeddings

In [212]:
lr=0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net_2.parameters(), lr=lr)

In [201]:
epochs = 10
counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net_2.cuda()
    gg.cuda()
gg.eval()
net_2.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    net_2.train()
    h = net_2.init_hidden(batch_size)
    # batch loop
    for inputs, labels in train_loader:
        counter += 1
        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()
            inputs=torch.tensor(inputs).to(torch.int64)
            labels=torch.tensor(labels).to(torch.long)

        h = tuple([each.data for each in h])
        net_2.zero_grad()
        inputs=torch.tensor(inputs).to(torch.int64)
        labels=torch.tensor(labels).to(torch.long)
        net_2.train()
        embed=gg(inputs)
        output, h = net_2(embed, h)

        # calculate the loss and perform backprop
        loss = criterion(output, labels)
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net_2.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            net_1.eval()
            val_h = net_2.init_hidden(batch_size)
            val_losses = []
            a=[]
            net_1.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                
                val_h = tuple([each.data for each in val_h])
                inputs=torch.tensor(inputs).to(torch.int64)
                labels=torch.tensor(labels).to(torch.long)
                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()
                    inputs=torch.tensor(inputs).to(torch.int64)
                    labels=torch.tensor(labels).to(torch.long)

                embed=gg(inputs)
                output, val_h = net_2(embed, val_h)
                _,index=torch.topk(output,1)
                val_loss = criterion(output, labels)
                a.append(index.item()==labels.item())
            a=100*((a.count(1))/(a.count(0)+a.count(1)))
                

            val_losses.append(val_loss.item())
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.9f}...".format(loss.item()),
                  "Val Accuracy: {:.2f}%...".format(a),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\lib\site-packages\ipykernel_launcher.py:28: UserWarning: To copy construct from a te

RuntimeError: leaf variable has been moved into the graph interior

tensor([1], device='cuda:0')

In [112]:
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])

In [113]:
net_1.embedding(input)

tensor([[[-0.2293,  0.8980,  0.0916,  ...,  0.1030, -0.4555,  0.1457],
         [-0.3443,  0.1976, -0.4041,  ...,  1.4874,  1.6619, -1.9421],
         [ 2.0021, -0.5411,  0.3348,  ..., -0.4410, -1.4665, -1.4666],
         [-1.4639, -1.4073,  0.5237,  ...,  0.0995,  1.2004, -0.0285]],

        [[ 2.0021, -0.5411,  0.3348,  ..., -0.4410, -1.4665, -1.4666],
         [-0.9742,  1.2988, -1.2953,  ..., -0.6601,  1.0600, -0.3606],
         [-0.3443,  0.1976, -0.4041,  ...,  1.4874,  1.6619, -1.9421],
         [-1.3222,  1.3495, -1.5036,  ..., -0.7361,  0.6563,  0.0972]]],
       grad_fn=<EmbeddingBackward>)

In [64]:
net_1.embedding.weight

Parameter containing:
tensor([[-2.7655e-01,  1.0842e+00, -2.0595e+00,  ..., -5.9035e-01,
          9.9509e-01,  1.5742e+00],
        [ 4.3328e-01, -6.1953e-02, -9.6089e-02,  ..., -1.2927e+00,
         -8.9933e-01,  6.1164e-02],
        [-3.6420e-01,  6.4138e-01, -1.5965e+00,  ...,  3.2847e-01,
         -1.7789e+00,  2.6770e-01],
        ...,
        [ 1.5111e+00, -9.9730e-01, -1.4124e+00,  ...,  4.6116e-02,
          9.1095e-01,  5.6723e-02],
        [-1.1536e+00, -2.4567e-01,  4.1004e-01,  ..., -3.1223e+00,
          1.2800e-01,  6.4361e-01],
        [ 1.0157e+00,  2.8516e-01, -4.8914e-02,  ...,  5.9363e-01,
         -2.5761e-03,  2.3110e-01]], device='cuda:0', requires_grad=True)

In [65]:
torch.save(net_1.state_dict(),"ieeesite_v2.pt")

In [213]:
outputs,_=net_2(gg(inputs),net_2.init_hidden(1))

In [217]:
loss = criterion(output, labels)
loss.backward(retain_graph=True)
      # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
nn.utils.clip_grad_norm_(net_2.parameters(), clip)
optimizer.step()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

Word2vec_Embed(
  (embedding): Embedding(939, 300)
)

In [277]:


import sys
print(sys.executable)


C:\Users\Guru Aathavan AL U\anaconda3\envs\torch\python.exe


In [49]:
word_to_int

{'recognize': 1,
 'someone': 2812,
 'with': 1839,
 'sense': 4,
 'confidence': 5,
 'timely': 3519,
 'clubs': 239,
 'haunt': 8,
 'loanword': 9,
 'assure': 2348,
 'i': 3065,
 'theater': 12,
 'assort': 13,
 'astir': 676,
 'excessively': 15,
 'that': 1847,
 'sees': 17,
 'dress': 849,
 'universal': 3833,
 'pls': 3829,
 'followed': 21,
 'shop': 1307,
 'wherefore': 1665,
 'streaming': 2585,
 'tactual': 25,
 'xiii': 26,
 'bathroom': 27,
 'need': 3722,
 'internet': 1565,
 'watching': 3908,
 "you't": 31,
 'baltic': 1062,
 'noblewoman': 33,
 'mode': 34,
 'gravel': 35,
 'agency': 36,
 'hypothetical': 1399,
 'treating': 2530,
 '6': 39,
 'honey': 40,
 'my': 3843,
 'suggest': 42,
 'hiring': 703,
 'nor': 44,
 'bot': 2823,
 'protect': 46,
 "ieee'em": 47,
 'towards': 48,
 'users': 49,
 'hullo': 2828,
 'destiny': 51,
 'machinate': 52,
 'firmly': 53,
 'dead': 54,
 'emcee': 55,
 'apace': 56,
 'there': 3850,
 'you': 2584,
 'organizing': 59,
 'must': 1685,
 'end': 830,
 'function': 62,
 'interactional': 63,
 

In [50]:
import pickle

In [56]:
f=open("word_to_int.pkl","wb")
pickle.dump(word_to_int,f)
f.close()
f=open("int_to_word.pkl","wb")
pickle.dump(int_to_word,f)
f.close()

In [62]:
f=open("int_to_label.pkl","wb")
pickle.dump(int_to_label,f)
f.close()
f=open("label_to_int.pkl","wb")
pickle.dump(label_to_int,f)
f.close()